- name: adding encrypted  password to the user 
  hosts: sys2
  become: yes
  vars:
    mypass: srikar
  tasks:
    - name: Adding user and password
      ansible.builtin.user:
        name: harshu
        state: present
        uid: 5000
        password: "{{mypass | password_hash('sha512') }}"
